name: lasuite

include:
  - interop/compose.yml

services:
  menshen-postgresql:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 2s
      retries: 300
    env_file:
      - env.d/development/postgresql
      - env.d/development/postgresql.local
    networks:
      - lasuite
    ports:
      - "9001:5432"

  menshen-backend:
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
      target: backend-development
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: menshen:backend-development
    environment:
      - DJANGO_CONFIGURATION=Development
    env_file:
      - env.d/development/common
      - env.d/development/common.local
      - env.d/development/postgresql
      - env.d/development/postgresql.local
    networks:
      - lasuite
    ports:
      - "9000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8000/__heartbeat__"]
      interval: 1s
      timeout: 2s
      retries: 300
    volumes:
      - ./src/backend:/app
      - ./data/static:/data/static
    depends_on:
      menshen-postgresql:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
      keycloak:
        condition: service_healthy

  menshen-playground-source:
    build:
      context: .
      dockerfile: ./src/playground/source/Dockerfile
      target: backend-development
    image: menshen:playground-source
    networks:
      - lasuite
    ports:
      - "9002:8000"
    develop:
      watch:
        - action: sync+restart
          path: ./src/playground/source
          target: /app
          ignore:
            - ./src/playground/source/.venv/
        - action: rebuild
          path: ./src/playground/source/uv.lock
        - action: rebuild
          path: ./src/playground/source/Dockerfile
    depends_on:
      keycloak:
        condition: service_healthy
      menshen-backend:
        condition: service_healthy

  menshen-playground-target:
    build:
      context: .
      dockerfile: ./src/playground/target/Dockerfile
      target: backend-development
    image: menshen:playground-target
    networks:
      - lasuite
    ports:
      - "9003:8000"
    develop:
      watch:
        - action: sync+restart
          path: ./src/playground/target
          target: /app
          ignore:
            - ./src/playground/target/.venv/
        - action: rebuild
          path: ./src/playground/target/uv.lock
        - action: rebuild
          path: ./src/playground/target/Dockerfile
    depends_on:
      keycloak:
        condition: service_healthy
      menshen-backend:
        condition: service_healthy

  # Utils
  openssl:
    image: alpine/openssl:3.5.7

networks:
  lasuite:
    name: lasuite

volumes:
  venv:
