# Generated by Django 6.0.3 on 2026-10-02 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('sub', models.CharField(blank=True, help_text='Required. 255 characters or fewer. ASCII characters only.', max_length=255, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Identity email address')),
                ('name', models.CharField(blank=True, help_text='Name of the user.', max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Whether the user can log into this admin site.')),
                ('is_superuser', models.BooleanField(default=False, help_text='Whether the user is a super user.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting', models.CharField(help_text='Meeting name')),
                ('meeting_id', models.UUIDField(help_text='Meeting identifier')),
                ('duration', models.IntegerField(help_text='Recording duration (in seconds)')),
                ('held_at', models.DateTimeField(help_text='Meeting date & time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'recordings',
                'ordering': ['-held_at'],
            },
        ),
    ]
