# Generated by Django 6.0.3 on 2026-04-06 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting', models.CharField(help_text='Meeting name')),
                ('meeting_id', models.UUIDField(help_text='Meeting identifier')),
                ('duration', models.IntegerField(help_text='Recording duration (in seconds)')),
                ('held_at', models.DateTimeField(help_text='Meeting date & time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'recording',
                'ordering': ['created_at'],
            },
        ),
    ]
