# Generated by Django 6.0.4 on 2026-05-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedtoken',
            name='token',
            field=models.TextField(db_index=True, help_text='The actual token string (opaque or JWT)', unique=True, verbose_name='Token'),
        ),
    ]
