# Generated by Django 6.0.7 on 2026-08-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_exchange', '0002_alter_exchangedtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedtoken',
            name='token_type',
            field=models.CharField(choices=[('urn:ietf:params:oauth:token-type:access_token', 'Access Token'), ('urn:ietf:params:oauth:token-type:jwt', 'JWT')], default='urn:ietf:params:oauth:token-type:access_token', help_text='The type of token as per RFC 8693', max_length=50, verbose_name='Token Type'),
        ),
    ]
