# Generated by Django 6.1 on 2026-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_exchange', '0003_alter_exchangedtoken_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovidercredentials',
            name='client_secret',
            field=models.CharField(editable=False, max_length=255, verbose_name='Client secret'),
        ),
    ]
