# Generated by Django 6.1 on 2026-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_exchange', '0004_alter_serviceprovidercredentials_client_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedtoken',
            name='subject_token_jti',
            field=models.CharField(blank=True, db_index=True, help_text='The JTI of the original SSO token for traceability', max_length=255, verbose_name='Subject Token JTI'),
        ),
    ]
