# Default values for menshen.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section General configuration

## @param image.repository Repository to use to pull menshen's container image
## @param image.tag menshen's container tag
## @param image.pullPolicy Container image pull policy
## @extra image.credentials.username Username for container registry authentication
## @extra image.credentials.password Password for container registry authentication
## @extra image.credentials.registry Registry url for which the credentials are specified
## @extra image.credentials.name Name of the generated secret for imagePullSecrets
image:
  repository: lasuite/menshen-backend
  pullPolicy: IfNotPresent
  tag: "latest"

## @param nameOverride Override the chart name
## @param fullnameOverride Override the full application name
nameOverride: ""
fullnameOverride: ""

## @skip commonEnvVars
commonEnvVars: &commonEnvVars
  <<: []

## @param ingress.enabled whether to enable the Ingress or not
## @param ingress.className IngressClass to use for the Ingress
## @param ingress.host Host for the Ingress
## @param ingress.path Path to use for the Ingress
ingress:
  enabled: false
  className: null
  host: menshen.example.com
  path: /
  ## @param ingress.hosts Additional host to configure for the Ingress
  hosts: []
  #  - chart-example.local
  ## @param ingress.tls.enabled Whether to enable TLS for the Ingress
  ## @param ingress.tls.secretName Secret name for TLS config
  ## @skip ingress.tls.additional
  ## @extra ingress.tls.additional[].secretName Secret name for additional TLS config
  ## @extra ingress.tls.additional[].hosts[] Hosts for additional TLS config
  tls:
    enabled: true
    secretName: null
    additional: []

  ## @param ingress.customBackends Add custom backends to ingress
  customBackends: []

## @param ingressAdmin.enabled whether to enable the Ingress or not
## @param ingressAdmin.className IngressClass to use for the Ingress
## @param ingressAdmin.host Host for the Ingress
## @param ingressAdmin.path Path to use for the Ingress
ingressAdmin:
  enabled: false
  className: null
  host: menshen.example.com
  path: /admin
  ## @param ingressAdmin.hosts Additional host to configure for the Ingress
  hosts: []
  #  - chart-example.local
  ## @param ingressAdmin.tls.enabled Whether to enable TLS for the Ingress
  ## @param ingressAdmin.tls.secretName Secret name for TLS config
  ## @skip ingressAdmin.tls.additional
  ## @extra ingressAdmin.tls.additional[].secretName Secret name for additional TLS config
  ## @extra ingressAdmin.tls.additional[].hosts[] Hosts for additional TLS config
  tls:
    enabled: true
    secretName: null
    additional: []

## @section backend

backend:
  ## @param backend.command Override the backend container command
  command: []

  ## @param backend.args Override the backend container args
  args: []

  ## @param backend.replicas Amount of backend replicas
  replicas: 3

  ## @param backend.shareProcessNamespace Enable share process namespace between containers
  shareProcessNamespace: false

  ## @param backend.sidecars Add sidecars containers to backend deployment
  sidecars: []

  ## @param backend.migrateJobAnnotations Annotations for the migrate job
  migrateJobAnnotations: {}

  ## @param backend.jobs.ttlSecondsAfterFinished Period to wait before remove jobs
  ## @param backend.jobs.backoffLimit Numbers of jobs retries
  jobs:
    ttlSecondsAfterFinished: 30
    backoffLimit: 2

  ## @param backend.securityContext.allowPrivilegeEscalation Whether to allow privilege escalation for the backend container
  ## @param backend.securityContext.capabilities.drop List of capabilities to drop for the backend container
  ## @param backend.securityContext.runAsNonRoot Whether to run the backend container as a non-root user
  ## @param backend.securityContext.seccompProfile.type Seccomp profile type for the backend container
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - "ALL"
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  ## @param backend.envVars Configure backend container environment variables
  ## @extra backend.envVars.BY_VALUE Example environment variable by setting value directly
  ## @extra backend.envVars.FROM_CONFIGMAP.configMapKeyRef.name Name of a ConfigMap when configuring env vars from a ConfigMap
  ## @extra backend.envVars.FROM_CONFIGMAP.configMapKeyRef.key Key within a ConfigMap when configuring env vars from a ConfigMap
  ## @extra backend.envVars.FROM_SECRET.secretKeyRef.name Name of a Secret when configuring env vars from a Secret
  ## @extra backend.envVars.FROM_SECRET.secretKeyRef.key Key within a Secret when configuring env vars from a Secret
  ## @skip backend.envVars
  envVars:
    <<: *commonEnvVars

  ## @skip backend.envFrom List of environment variables taken from Secrets or configMaps, common to backend and celery worker
  envFrom: []
  # envFrom:
  #   - secret:
  #       name: super-secret-user-credentials
  #   - configMapRef:
  #       name: my-environment-variables

  ## @extra backend.django.envVars Backend web deployment specific environment variables (not shared with celery worker)
  ## @skip backend.django.envVars
  ## @skip backend.django.envFrom List of environment variables taken from Secrets or configMaps, specific to the backend web deployment
  django:
    envVars: {}
    envFrom: []

  ## @param backend.podAnnotations Annotations to add to the backend Pod
  podAnnotations: {}

  ## @param backend.dpAnnotations Annotations to add to the backend Deployment
  dpAnnotations: {}

  ## @param backend.service.type backend Service type
  ## @param backend.service.port backend Service listening port
  ## @param backend.service.targetPort backend container listening port
  ## @param backend.service.annotations Annotations to add to the backend Service
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
    annotations: {}

  ## @param backend.migrate.command backend migrate command
  ## @param backend.migrate.restartPolicy backend migrate job restart policy
  migrate:
    command:
      - /bin/sh
      - "-c"
      - |
        while ! python manage.py check --database default > /dev/null 2>&1
        do
          echo "Database not ready"
          sleep 2
        done

        echo "Database is ready"

        python manage.py migrate --no-input
    restartPolicy: Never

  ## @param backend.createsuperuser.command backend migrate command
  ## @param backend.createsuperuser.restartPolicy backend migrate job restart policy
  createsuperuser:
    command:
      - "/bin/sh"
      - "-c"
      - |
        while ! python manage.py check --database default > /dev/null 2>&1
        do
          echo "Database not ready"
          sleep 2
        done

        echo "Database is ready"

        python manage.py createsuperuser --email $DJANGO_SUPERUSER_EMAIL --password $DJANGO_SUPERUSER_PASSWORD
    restartPolicy: Never

  ## @extra backend.job job dedicated to run a random management command, for example after a deployment
  ## @param backend.job.name The name to use to describe this job
  ## @param backend.job.command The management command to execute
  ## @param backend.job.restartPolicy The restart policy for the job.
  ## @extra backend.job.annotations Annotations to add to the job [default: argocd.argoproj.io/hook: PostSync]
  ## @skip backend.job.annotations.argocd.argoproj.io/hook
  job:
    name: ""
    command: []
    restartPolicy: Never
    annotations:
      argocd.argoproj.io/hook: PostSync

  # List of cronjob to add
  # cronjobs:
  #   - name: reset-database
  #     schedule: "0 */2 * * *"
  #     command:
  #       - "/bin/sh"
  #       - "-c"
  #       - python manage.py flush --no-input
  ## @param backend.cronjobs Cronjob name, schedule, command
  cronjobs: []

  ## @param backend.probes.liveness.path [nullable] Configure path for backend HTTP liveness probe
  ## @param backend.probes.liveness.targetPort [nullable] Configure port for backend HTTP liveness probe
  ## @param backend.probes.liveness.initialDelaySeconds [nullable] Configure initial delay for backend liveness probe
  ## @param backend.probes.liveness.timeoutSeconds [nullable] Configure timeout for backend liveness probe
  ## @extra backend.probes.startup.path [nullable] Configure path for backend HTTP startup probe
  ## @extra backend.probes.startup.targetPort [nullable] Configure port for backend HTTP startup probe
  ## @extra backend.probes.startup.initialDelaySeconds [nullable] Configure initial delay for backend startup probe
  ## @extra backend.probes.startup.timeoutSeconds [nullable] Configure timeout for backend startup probe
  ## @param backend.probes.readiness.path [nullable] Configure path for backend HTTP readiness probe
  ## @param backend.probes.readiness.targetPort [nullable] Configure port for backend HTTP readiness probe
  ## @param backend.probes.readiness.initialDelaySeconds [nullable] Configure initial delay for backend readiness probe
  ## @param backend.probes.readiness.timeoutSeconds [nullable] Configure timeout for backend readiness probe
  probes:
    liveness:
      path: /__lbheartbeat__
      initialDelaySeconds: 10
    readiness:
      path: /__heartbeat__
      initialDelaySeconds: 10

  ## @param backend.resources Resource requirements for the backend container
  resources: {}

  ## @param backend.nodeSelector Node selector for the backend Pod
  nodeSelector: {}

  ## @param backend.tolerations Tolerations for the backend Pod
  tolerations: []

  ## @param backend.affinity Affinity for the backend Pod
  affinity: {}

  ## @param backend.persistence Additional volumes to create and mount on the backend. Used for debugging purposes
  ## @extra backend.persistence.volume-name.size Size of the additional volume
  ## @extra backend.persistence.volume-name.type Type of the additional volume, persistentVolumeClaim or emptyDir
  ## @extra backend.persistence.volume-name.mountPath Path where the volume should be mounted to
  persistence: {}

  ## @param backend.extraVolumeMounts Additional volumes to mount on the backend.
  extraVolumeMounts: []

  ## @param backend.extraVolumes Additional volumes to mount on the backend.
  extraVolumes: []

  ## @param backend.pdb.enabled Enable pdb on backend
  pdb:
    enabled: true

  ## @param backend.serviceAccountName Optional service account name to use for backend pods
  serviceAccountName: null
