name: Helmfile lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
    paths:
      - src/helm/menshen/**

permissions: {}

jobs:
  helmfile-lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/helmfile/helmfile:v1.5.2
    steps:

    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Helmfile lint
      run: helmfile -e dev -f src/helm/helmfile.yaml.gotmpl lint
